CursoSwitcher/Controllers/LogOutController.cs
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Mvc;

namespace CursoSwitcher.Controllers
{
    public class LogOutController : Controller
    {
        [HttpGet]
        public IActionResult Index()
        {
            HttpContext.SignOutAsync();
            return RedirectToAction("Index", "Login");
        }
    }
}

CursoSwitcher/Controllers/LoginController.cs
using Microsoft.AspNetCore.Mvc;
using CursoSwitcher.Models;
using System.Diagnostics;
using Microsoft.AspNetCore.Authentication.Cookies;
using System.Security.Claims;
using Microsoft.AspNetCore.Authentication;

namespace CursoSwitcher.Controllers
{
    public class LoginController : Controller
    {
        private readonly ModelContextManager _context;

        public LoginController(ModelContextManager context)
        {
            _context = context;
        }

        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }

        // Método donde vamos a setear las cookies al momento de iniciar sesión.
        private ClaimsPrincipal SetCookies(ProfileModel entity)
        {
            ClaimsIdentity identity = new ClaimsIdentity(CookieAuthenticationDefaults.AuthenticationScheme);
            identity.AddClaim(new Claim(ClaimTypes.Name, entity.Name));
            identity.AddClaim(new Claim(ClaimTypes.Role, entity.Is_moderator ? "ADMIN" : "USER"));
            identity.AddClaim(new Claim(ClaimTypes.NameIdentifier, entity.Id.ToString()));
            identity.AddClaim(new Claim(ClaimTypes.GivenName, entity.Name));

            ClaimsPrincipal principal = new ClaimsPrincipal(identity);
            return principal;
        }

        private bool UserValidation(String dni, String password)
        {
            bool loged = false;
            var user = _context.Profiles.SingleOrDefault(o => o.Dni.Equals(dni) && o.Password.Equals(password));

            if (user != null) {
                ClaimsPrincipal cookie = SetCookies(user);
                HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, cookie).Wait();
                loged = true;
            }
            return loged;
        }


        [HttpPost]
        public IActionResult Index(String dni, String password)
        {
            if (UserValidation(dni, password))
            {
                return RedirectToAction("Index", "Dashboard");
            } else
            {
                TempData["Message"] = "No se encontró al alumno, verifique sus credenciales.";
                return View();
            }
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

CursoSwitcher/Controllers/SignUpController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using CursoSwitcher.Models;

namespace CursoSwitcher.Controllers
{
    public class SignUpController : Controller
    {
        private readonly ModelContextManager _context;

        public SignUpController(ModelContextManager context)
        {
            _context = context;
        }

        [HttpGet]
        public IActionResult Index()
        {
            ViewData["CampusId"] = new SelectList(_context.Campus, "Id", "Name");
            ViewData["CareerId"] = new SelectList(_context.Careers, "Id", "Name");
            ViewData["CourseId"] = new SelectList(_context.Courses, "Id", "Name");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Index([Bind("Id,Name,Last_name,Dni,Password,Email,CourseId,CareerId,CampusId")] ProfileModel profileModel)
        {
            bool userExists = _context.Profiles.Any(e => e.Email.Equals(profileModel.Email) || e.Dni.Equals(profileModel.Dni));
            if (!userExists)
            {
                _context.Add(profileModel);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index", "Login");
            }
            ViewData["CampusId"] = new SelectList(_context.Campus, "Id", "Name");
            ViewData["CareerId"] = new SelectList(_context.Careers, "Id", "Name");
            ViewData["CourseId"] = new SelectList(_context.Courses, "Id", "Name");
            TempData["Message"] = "Ya existe actualmente una cuenta con ese correo electrónico o documento.";
            return View(profileModel);
        }

    }
}

CursoSwitcher/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Course Exchanger</title>    
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CursoSwitcher.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/navbar.css" asp-append-version="true" />
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
</head>
<body>
    <header>
        <nav id="navbarOrt" class="navbar navbar-expand-sm navbar-toggleable-sm border-bottom box-shadow mb-3">
            <div class="container-fluid">
                @if(User.Identity.IsAuthenticated)
                {
                    <a class="navbar-brand links" asp-area="" asp-controller="Dashboard" asp-action="Index">Course Exchanger</a>                        
                } else
                {
                    <a class="navbar-brand links" asp-area="" asp-controller="Login" asp-action="Index">Course Exchanger</a>                    
                }
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        @if(User.Identity.IsAuthenticated) 
                        {
                        <li class="nav-item">
                            <a class="nav-link links" asp-area="">Bienvenido, @User.Identity.Name</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link links" asp-area="" asp-controller="LogOut" asp-action="Index">Desconectarse</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link links" asp-area="" asp-controller="Dashboard" asp-action="Index">Mis solicitudes</a>
                        </li>
                        } else {
                        <li class="nav-item">
                            <a class="nav-link links" asp-area="" asp-controller="Login" asp-action="Index">Iniciar Sesión</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link links" asp-area="" asp-controller="SignUp" asp-action="Index">Registrarse</a>
                        </li>
                        }
                        @if (User.IsInRole("ADMIN"))
                        {
                        <li class="nav-item">
                            <a class="nav-link links" asp-area="" asp-controller="BackOffice" asp-action="Index">BackOffice</a>
                        </li>                            
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <!--
    <footer class="mt-auto footer border-top text-muted">
        <div class="container">
            &copy; 2022 - Course Exchanger | Diaz Federico, Mariño Augusto, Popov Alexei | Programación de Nuevas Tecnologías 1 
        </div>
    </footer>
    -->
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/script.js" asp-append-version="true"></script>
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>