CursoSwitcher/Controllers/CampusController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using CursoSwitcher.Models;
using Microsoft.AspNetCore.Authorization;

namespace CursoSwitcher.Controllers
{
    [Authorize(Roles = "ADMIN")]
    public class CampusController : Controller
    {
        private readonly ModelContextManager _context;

        public CampusController(ModelContextManager context)
        {
            _context = context;
        }

        // GET: Campus
        public async Task<IActionResult> Index()
        {
              return _context.Campus != null ? 
                          View(await _context.Campus.ToListAsync()) :
                          Problem("Entity set 'ModelContextManager.Campus'  is null.");
        }

        // GET: Campus/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Campus == null)
            {
                return NotFound();
            }

            var campusModel = await _context.Campus
                .FirstOrDefaultAsync(m => m.Id == id);
            if (campusModel == null)
            {
                return NotFound();
            }

            return View(campusModel);
        }

        // GET: Campus/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Campus/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Description,Visible_id,Created_at,Updated_at")] CampusModel campusModel)
        {
            if (ModelState.IsValid)
            {
                _context.Add(campusModel);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(campusModel);
        }

        // GET: Campus/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Campus == null)
            {
                return NotFound();
            }

            var campusModel = await _context.Campus.FindAsync(id);
            if (campusModel == null)
            {
                return NotFound();
            }
            return View(campusModel);
        }

        // POST: Campus/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Description,Visible_id,Created_at,Updated_at")] CampusModel campusModel)
        {
            if (id != campusModel.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(campusModel);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CampusModelExists(campusModel.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(campusModel);
        }

        // GET: Campus/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Campus == null)
            {
                return NotFound();
            }

            var campusModel = await _context.Campus
                .FirstOrDefaultAsync(m => m.Id == id);
            if (campusModel == null)
            {
                return NotFound();
            }

            return View(campusModel);
        }

        // POST: Campus/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Campus == null)
            {
                return Problem("Entity set 'ModelContextManager.Campus'  is null.");
            }
            var campusModel = await _context.Campus.FindAsync(id);
            var hasProfileRelated = _context.Profiles.Any(p => p.CampusId == id); 
            if (campusModel != null && !hasProfileRelated)
            {
                _context.Campus.Remove(campusModel);
            } else
            {
                TempData["CannotDelete"] = "No puede borrar una sede con alumnos asociadas a ella.";
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CampusModelExists(int id)
        {
          return (_context.Campus?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

CursoSwitcher/Controllers/CareerController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using CursoSwitcher.Models;
using Microsoft.AspNetCore.Authorization;

namespace CursoSwitcher.Controllers
{
    [Authorize(Roles = "ADMIN")]
    public class CareerController : Controller
    {
        private readonly ModelContextManager _context;

        public CareerController(ModelContextManager context)
        {
            _context = context;
        }

        // GET: Career
        public async Task<IActionResult> Index()
        {
              return _context.Careers != null ? 
                          View(await _context.Careers.ToListAsync()) :
                          Problem("Entity set 'ModelContextManager.Careers'  is null.");
        }

        // GET: Career/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Careers == null)
            {
                return NotFound();
            }

            var careerModel = await _context.Careers
                .FirstOrDefaultAsync(m => m.Id == id);
            if (careerModel == null)
            {
                return NotFound();
            }

            return View(careerModel);
        }

        // GET: Career/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Career/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Description,Visible_id,Created_at,Updated_at")] CareerModel careerModel)
        {
            if (ModelState.IsValid)
            {
                _context.Add(careerModel);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(careerModel);
        }

        // GET: Career/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Careers == null)
            {
                return NotFound();
            }

            var careerModel = await _context.Careers.FindAsync(id);
            if (careerModel == null)
            {
                return NotFound();
            }
            return View(careerModel);
        }

        // POST: Career/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Description,Visible_id,Created_at,Updated_at")] CareerModel careerModel)
        {
            if (id != careerModel.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(careerModel);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CareerModelExists(careerModel.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(careerModel);
        }

        // GET: Career/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Careers == null)
            {
                return NotFound();
            }

            var careerModel = await _context.Careers
                .FirstOrDefaultAsync(m => m.Id == id);
            if (careerModel == null)
            {
                return NotFound();
            }

            return View(careerModel);
        }

        // POST: Career/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Careers == null)
            {
                return Problem("Entity set 'ModelContextManager.Careers'  is null.");
            }
            var careerModel = await _context.Careers.FindAsync(id);
            var hasProfileRelated = _context.Profiles.Any(p => p.CampusId == id);
            var hasCoursesRelated = _context.Courses.Any(c => c.CareerId == id);
            if (careerModel != null && !(hasProfileRelated || hasCoursesRelated))
            {
                _context.Careers.Remove(careerModel);
            }
            else
            {
                TempData["CannotDelete"] = "No puede borrar una carrera con alumnos o cursos asociadas a ella.";
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CareerModelExists(int id)
        {
          return (_context.Careers?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

CursoSwitcher/Controllers/CoursesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CursoSwitcher.Models;
using Microsoft.AspNetCore.Authorization;

namespace CursoSwitcher.Controllers
{
    [Authorize(Roles = "ADMIN")]
    public class CoursesController : Controller
    {
        private readonly ModelContextManager _context;

        public CoursesController(ModelContextManager context)
        {
            _context = context;
        }

        // GET: Courses
        public async Task<IActionResult> Index()
        {
            var modelContextManager = _context.Courses.Include(c => c.Career);
            return View(await modelContextManager.ToListAsync());
        }

        // GET: Courses/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Courses == null)
            {
                return NotFound();
            }

            var coursesModel = await _context.Courses
                .Include(c => c.Career)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (coursesModel == null)
            {
                return NotFound();
            }

            return View(coursesModel);
        }

        // GET: Courses/Create
        public IActionResult Create()
        {
            ViewData["CareerId"] = new SelectList(_context.Careers, "Id", "Name");
            return View();
        }

        // POST: Courses/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Description,CareerId,Visible_id,Created_at,Updated_at")] CoursesModel coursesModel)
        {
            if (ModelState.IsValid)
            {
                _context.Add(coursesModel);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["CareerId"] = new SelectList(_context.Careers, "Id", "Name", coursesModel.CareerId);
            return View(coursesModel);
        }

        // GET: Courses/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Courses == null)
            {
                return NotFound();
            }

            var coursesModel = await _context.Courses.FindAsync(id);
            if (coursesModel == null)
            {
                return NotFound();
            }
            ViewData["CareerId"] = new SelectList(_context.Careers, "Id", "Name", coursesModel.CareerId);
            return View(coursesModel);
        }

        // POST: Courses/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Description,CareerId,Visible_id,Created_at,Updated_at")] CoursesModel coursesModel)
        {
            if (id != coursesModel.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(coursesModel);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CoursesModelExists(coursesModel.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["CareerId"] = new SelectList(_context.Careers, "Id", "Name", coursesModel.CareerId);
            return View(coursesModel);
        }

        // GET: Courses/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Courses == null)
            {
                return NotFound();
            }

            var coursesModel = await _context.Courses
                .Include(c => c.Career)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (coursesModel == null)
            {
                return NotFound();
            }

            return View(coursesModel);
        }

        // POST: Courses/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Courses == null)
            {
                return Problem("Entity set 'ModelContextManager.Courses'  is null.");
            }
            var coursesModel = await _context.Courses.FindAsync(id);
            var hasProfileRelated = _context.Profiles.Any(p => p.CourseId == id);
            if (coursesModel != null && !hasProfileRelated)
            {
                _context.Courses.Remove(coursesModel);
            } else
            {
                TempData["CannotDelete"] = "No puede borrar un curso con alumnos inscriptos en ella.";
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CoursesModelExists(int id)
        {
          return (_context.Courses?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

CursoSwitcher/Views/BackOffice/Index.cshtml
<link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
@{
    var STATUS_PIE_CHART_TITLE = "Solicitudes según su estado";
    var REQUEST_FREQUENCY_TITLE = "Frecuencia de solicitudes";
}
<h1>BackOffice - Course Exchanger</h1>
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/3.8.0/chart.js" crossorigin="anonymous"></script>
<hr />
<div class="container-fluid">
  <div class="row">
    <div class="col-sm buttonOrt">
      <a class="links" asp-area="" asp-controller="Campus" asp-action="Index">Administrar Sedes</a>   
    </div>
    <div class="col-sm buttonOrt">
      <a class="links" asp-area="" asp-controller="Career" asp-action="Index">Administrar Carreras</a>
    </div>
    <div class="col-sm buttonOrt">
      <a  class="links" asp-area="" asp-controller="Courses" asp-action="Index">Administrar Cursos</a>
    </div>
    <div class="col-sm buttonOrt">
      <a class="links" asp-area="" asp-controller="Profile" asp-action="Index">Administrar Perfiles</a>
    </div>
    <div class="col-sm buttonOrt">
      <a class="links" asp-area="" asp-controller="Requests" asp-action="Index">
          Administrar Peticiones
          @if (@ViewBag.RequestsByStatusPendiente > 0)
          {
                <span class="badge badge-warning" data-toggle="tooltip" title="Solicitudes pendientes">@ViewBag.RequestsByStatusPendiente</span>   
          } else if ((@ViewBag.RequestsByStatusPendiente > 5))
          {
                <span class="badge badge-danger" data-toggle="tooltip" title="Solicitudes pendientes">@ViewBag.RequestsByStatusPendiente</span>
          } else
          {
                <span class="badge badge-light" data-toggle="tooltip" title="Solicitudes pendientes">@ViewBag.RequestsByStatusPendiente</span>    
          }
            </a>
    </div>
</div>

<div style="text-align:center">
<div style="display:inline-block;padding:20px;">
<h1>@STATUS_PIE_CHART_TITLE</h1>
<canvas id="pie_status_chart" width="400" height="400"></canvas>
</div>
<div style="display:inline-block;padding:20px;">
<h1>@REQUEST_FREQUENCY_TITLE</h1>
<canvas id="bar_frequency_chart" width="400" height="450"></canvas>
</div>
</div>




<script>
const ctx = document.getElementById('pie_status_chart').getContext('2d');
const myChart = new Chart(ctx, {
    type: 'pie',
    data: {
        labels: ["Aprobada", "Rechazada", "Pendiente", "Error"],
        datasets: [{
            label: 'Amount of requests with different status',
            data: [@ViewBag.RequestsByStatusAceptada, @ViewBag.RequestsByStatusRechazada, @ViewBag.RequestsByStatusPendiente, @ViewBag.RequestsByStatusError ],
            backgroundColor: [
                'rgba(54, 162, 235, 0.2)',
                'rgba(255, 99, 132, 0.2)',
                'rgba(255, 206, 86, 0.2)',
                'rgba(255, 0, 0, 0.2)',
            ],
            borderColor: [
                'rgba(54, 162, 235, 1)',
                'rgba(255, 99, 132, 1)',
                'rgba(255, 206, 86, 1)',
                'rgba(255, 0, 0, 1)',
            ],
            borderWidth: 3
        }]
    },
    options: {
        scales: {
            y: {
                beginAtZero: true
            }
        }
    }
});

const ctx2 = document.getElementById('bar_frequency_chart').getContext('2d');
const dias = ['Domingo', 'Lunes', 'Martes', 'Miercoles', 'Jueves', 'Viernes', 'Sabado']
const myChart2 = new Chart(ctx2, {
    type: 'bar',
    data: {
        labels: dias,
        datasets: [{
            label: "Julio",
            data: [
                @ViewBag.FrequencyByDayDuringTheMonth["Domingo"],
                @ViewBag.FrequencyByDayDuringTheMonth["Lunes"],
                @ViewBag.FrequencyByDayDuringTheMonth["Martes"],
                @ViewBag.FrequencyByDayDuringTheMonth["Miercoles"],
                @ViewBag.FrequencyByDayDuringTheMonth["Jueves"],
                @ViewBag.FrequencyByDayDuringTheMonth["Viernes"],
                @ViewBag.FrequencyByDayDuringTheMonth["Sabado"],
            ],
            backgroundColor: [
                'rgba(255, 99, 132, 0.2)',
                'rgba(54, 162, 235, 0.2)',
                'rgba(255, 206, 86, 0.2)',
                'rgba(75, 192, 192, 0.2)',
                'rgba(153, 102, 255, 0.2)',
                'rgba(153, 152, 92, 0.2)',
                'rgba(255, 159, 64, 0.2)'
            ],
            borderColor: [
                'rgba(255, 99, 132, 1)',
                'rgba(54, 162, 235, 1)',
                'rgba(255, 206, 86, 1)',
                'rgba(75, 192, 192, 1)',
                'rgba(153, 102, 255, 1)',
                'rgba(153, 152, 92, 1)',
                'rgba(255, 159, 64, 1)'
            ],
            borderWidth: 1
        }]
    },
    options: {
        scales: {
            y: {
                beginAtZero: true
            }
        }
    }
});
</script>


<br/>

</div>